#! /bin/sh
# Install all manual pages.

PREFIX=$1
for t in doc/*.[0-9]
do
    FILE=`expr $t : '^.*/\(.*\)$'`
    NUM=`expr $t : '^.*\.\([0-9]*\)$'`
    
    ./install-sh -c -m 644 $t $PREFIX/man/man$NUM/$FILE
done
