#!/bin/sh

prefix=/home/haeleth/svn/ponscripter/extlib
exec_prefix=${prefix}
exec_prefix_set=no

usage="\
Usage: smpeg-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--libs] [--cflags]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo $prefix
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo $exec_prefix
      ;;
    --version)
      echo 0.4.5
      ;;
    --cflags)
      if test ${prefix}/include != /usr/include ; then
        includes=-I${prefix}/include
      fi
      echo $includes -I${prefix}/include/smpeg `/home/haeleth/svn/ponscripter/extlib/bin/sdl-config --cflags`
      ;;
    --libs)
      if [ "`uname`" = "SunOS" ]; then
        libdirs="-L${exec_prefix}/lib -R${exec_prefix}/lib"
      else
        libdirs="-L${exec_prefix}/lib "
      fi
      echo $libdirs -lsmpeg `/home/haeleth/svn/ponscripter/extlib/bin/sdl-config --libs`
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done
